from __future__ import annotations
import datetime
from collections.abc import Callable
from dataclasses import dataclass, field
from kiota_abstractions.serialization import AdditionalDataHolder, Parsable, ParseNode, SerializationWriter
from typing import Any, Optional, TYPE_CHECKING, Union

if TYPE_CHECKING:
    from .sms_event_table_row_outbound_source import SmsEventTableRow_outboundSource
    from .sms_event_table_row_status import SmsEventTableRow_status
    from .sms_event_table_row_traffic_type import SmsEventTableRow_trafficType

@dataclass
class SmsEventTableRow(AdditionalDataHolder, Parsable):
    """
    API DTO containing SMS event data used by Leadping API contracts.
    """
    # Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additional_data: dict[str, Any] = field(default_factory=dict)

    # The actor display name associated with this SMS event.
    actor_display_name: Optional[str] = None
    # The actor user ID associated with this SMS event.
    actor_user_id: Optional[str] = None
    # The current billing status for this SMS event.
    billing_status: Optional[str] = None
    # The date and time for the blocked at value on this SMS event.
    blocked_at: Optional[datetime.datetime] = None
    # The business value for this SMS event.
    business: Optional[str] = None
    # The display name for the business associated with this SMS event.
    business_name: Optional[str] = None
    # The human-readable cancel reason explaining this SMS event.
    cancel_reason: Optional[str] = None
    # The date and time for the canceled at value on this SMS event.
    canceled_at: Optional[datetime.datetime] = None
    # The compliance action value for this SMS event.
    compliance_action: Optional[str] = None
    # The conversation ID associated with this SMS event.
    conversation_id: Optional[str] = None
    # The date and time for the created at value on this SMS event.
    created_at: Optional[datetime.datetime] = None
    # The date and time for the delivered at value on this SMS event.
    delivered_at: Optional[datetime.datetime] = None
    # The direction value for this SMS event.
    direction: Optional[str] = None
    # The error code value for this SMS event.
    error_code: Optional[str] = None
    # The error message value for this SMS event.
    error_message: Optional[str] = None
    # The date and time for the failed at value on this SMS event.
    failed_at: Optional[datetime.datetime] = None
    # The phone number associated with this SMS event.
    from_phone_number: Optional[str] = None
    # The from phone number ID associated with this SMS event.
    from_phone_number_id: Optional[str] = None
    # The unique ID for this SMS event.
    id: Optional[str] = None
    # Whether this SMS event was generated by automation.
    is_automated: Optional[bool] = None
    # Whether this SMS event is warmup.
    is_warmup: Optional[bool] = None
    # The lead ID associated with this SMS event.
    lead_id: Optional[str] = None
    # The display name for the lead associated with this SMS event.
    lead_name: Optional[str] = None
    # The outbound phone number ID associated with this SMS event.
    outbound_phone_number_id: Optional[str] = None
    # Defines the source that requested outbound delivery.
    outbound_source: Optional[SmsEventTableRow_outboundSource] = None
    # The provider message ID associated with this SMS event.
    provider_message_id: Optional[str] = None
    # The date and time for the queued at value on this SMS event.
    queued_at: Optional[datetime.datetime] = None
    # The date and time for the received at value on this SMS event.
    received_at: Optional[datetime.datetime] = None
    # The date and time for the scheduled for value on this SMS event.
    scheduled_for: Optional[datetime.datetime] = None
    # The human-readable scheduled reason explaining this SMS event.
    scheduled_reason: Optional[str] = None
    # The resolved display name for the party that sent the message.
    sender_name: Optional[str] = None
    # The date and time for the sending started at value on this SMS event.
    sending_started_at: Optional[datetime.datetime] = None
    # The date and time for the sent at value on this SMS event.
    sent_at: Optional[datetime.datetime] = None
    # Defines the supported SMS Message Status values.
    status: Optional[SmsEventTableRow_status] = None
    # The human-readable status reason explaining this SMS event.
    status_reason: Optional[str] = None
    # The Telnyx ID associated with this SMS event.
    telnyx_id: Optional[str] = None
    # The 10DLC campaign ID associated with this SMS event.
    ten_dlc_campaign_id: Optional[str] = None
    # The text value for this SMS event.
    text: Optional[str] = None
    # The phone number associated with this SMS event.
    to_phone_number: Optional[str] = None
    # Defines the supported SMS Traffic Type values.
    traffic_type: Optional[SmsEventTableRow_trafficType] = None
    # The date and time for the undeliverable at value on this SMS event.
    undeliverable_at: Optional[datetime.datetime] = None
    # The user value for this SMS event.
    user: Optional[str] = None
    # The display name for the user associated with this SMS event.
    user_name: Optional[str] = None
    
    @staticmethod
    def create_from_discriminator_value(parse_node: ParseNode) -> SmsEventTableRow:
        """
        Creates a new instance of the appropriate class based on discriminator value
        param parse_node: The parse node to use to read the discriminator value and create the object
        Returns: SmsEventTableRow
        """
        if parse_node is None:
            raise TypeError("parse_node cannot be null.")
        return SmsEventTableRow()
    
    def get_field_deserializers(self,) -> dict[str, Callable[[ParseNode], None]]:
        """
        The deserialization information for the current model
        Returns: dict[str, Callable[[ParseNode], None]]
        """
        from .sms_event_table_row_outbound_source import SmsEventTableRow_outboundSource
        from .sms_event_table_row_status import SmsEventTableRow_status
        from .sms_event_table_row_traffic_type import SmsEventTableRow_trafficType

        from .sms_event_table_row_outbound_source import SmsEventTableRow_outboundSource
        from .sms_event_table_row_status import SmsEventTableRow_status
        from .sms_event_table_row_traffic_type import SmsEventTableRow_trafficType

        fields: dict[str, Callable[[Any], None]] = {
            "actorDisplayName": lambda n : setattr(self, 'actor_display_name', n.get_str_value()),
            "actorUserId": lambda n : setattr(self, 'actor_user_id', n.get_str_value()),
            "billingStatus": lambda n : setattr(self, 'billing_status', n.get_str_value()),
            "blockedAt": lambda n : setattr(self, 'blocked_at', n.get_datetime_value()),
            "business": lambda n : setattr(self, 'business', n.get_str_value()),
            "businessName": lambda n : setattr(self, 'business_name', n.get_str_value()),
            "cancelReason": lambda n : setattr(self, 'cancel_reason', n.get_str_value()),
            "canceledAt": lambda n : setattr(self, 'canceled_at', n.get_datetime_value()),
            "complianceAction": lambda n : setattr(self, 'compliance_action', n.get_str_value()),
            "conversationId": lambda n : setattr(self, 'conversation_id', n.get_str_value()),
            "createdAt": lambda n : setattr(self, 'created_at', n.get_datetime_value()),
            "deliveredAt": lambda n : setattr(self, 'delivered_at', n.get_datetime_value()),
            "direction": lambda n : setattr(self, 'direction', n.get_str_value()),
            "errorCode": lambda n : setattr(self, 'error_code', n.get_str_value()),
            "errorMessage": lambda n : setattr(self, 'error_message', n.get_str_value()),
            "failedAt": lambda n : setattr(self, 'failed_at', n.get_datetime_value()),
            "fromPhoneNumber": lambda n : setattr(self, 'from_phone_number', n.get_str_value()),
            "fromPhoneNumberId": lambda n : setattr(self, 'from_phone_number_id', n.get_str_value()),
            "id": lambda n : setattr(self, 'id', n.get_str_value()),
            "isAutomated": lambda n : setattr(self, 'is_automated', n.get_bool_value()),
            "isWarmup": lambda n : setattr(self, 'is_warmup', n.get_bool_value()),
            "leadId": lambda n : setattr(self, 'lead_id', n.get_str_value()),
            "leadName": lambda n : setattr(self, 'lead_name', n.get_str_value()),
            "outboundPhoneNumberId": lambda n : setattr(self, 'outbound_phone_number_id', n.get_str_value()),
            "outboundSource": lambda n : setattr(self, 'outbound_source', n.get_enum_value(SmsEventTableRow_outboundSource)),
            "providerMessageId": lambda n : setattr(self, 'provider_message_id', n.get_str_value()),
            "queuedAt": lambda n : setattr(self, 'queued_at', n.get_datetime_value()),
            "receivedAt": lambda n : setattr(self, 'received_at', n.get_datetime_value()),
            "scheduledFor": lambda n : setattr(self, 'scheduled_for', n.get_datetime_value()),
            "scheduledReason": lambda n : setattr(self, 'scheduled_reason', n.get_str_value()),
            "senderName": lambda n : setattr(self, 'sender_name', n.get_str_value()),
            "sendingStartedAt": lambda n : setattr(self, 'sending_started_at', n.get_datetime_value()),
            "sentAt": lambda n : setattr(self, 'sent_at', n.get_datetime_value()),
            "status": lambda n : setattr(self, 'status', n.get_enum_value(SmsEventTableRow_status)),
            "statusReason": lambda n : setattr(self, 'status_reason', n.get_str_value()),
            "telnyxId": lambda n : setattr(self, 'telnyx_id', n.get_str_value()),
            "tenDlcCampaignId": lambda n : setattr(self, 'ten_dlc_campaign_id', n.get_str_value()),
            "text": lambda n : setattr(self, 'text', n.get_str_value()),
            "toPhoneNumber": lambda n : setattr(self, 'to_phone_number', n.get_str_value()),
            "trafficType": lambda n : setattr(self, 'traffic_type', n.get_enum_value(SmsEventTableRow_trafficType)),
            "undeliverableAt": lambda n : setattr(self, 'undeliverable_at', n.get_datetime_value()),
            "user": lambda n : setattr(self, 'user', n.get_str_value()),
            "userName": lambda n : setattr(self, 'user_name', n.get_str_value()),
        }
        return fields
    
    def serialize(self,writer: SerializationWriter) -> None:
        """
        Serializes information the current object
        param writer: Serialization writer to use to serialize this model
        Returns: None
        """
        if writer is None:
            raise TypeError("writer cannot be null.")
        writer.write_str_value("actorDisplayName", self.actor_display_name)
        writer.write_str_value("actorUserId", self.actor_user_id)
        writer.write_str_value("billingStatus", self.billing_status)
        writer.write_datetime_value("blockedAt", self.blocked_at)
        writer.write_str_value("business", self.business)
        writer.write_str_value("businessName", self.business_name)
        writer.write_str_value("cancelReason", self.cancel_reason)
        writer.write_datetime_value("canceledAt", self.canceled_at)
        writer.write_str_value("complianceAction", self.compliance_action)
        writer.write_str_value("conversationId", self.conversation_id)
        writer.write_datetime_value("createdAt", self.created_at)
        writer.write_datetime_value("deliveredAt", self.delivered_at)
        writer.write_str_value("direction", self.direction)
        writer.write_str_value("errorCode", self.error_code)
        writer.write_str_value("errorMessage", self.error_message)
        writer.write_datetime_value("failedAt", self.failed_at)
        writer.write_str_value("fromPhoneNumber", self.from_phone_number)
        writer.write_str_value("fromPhoneNumberId", self.from_phone_number_id)
        writer.write_str_value("id", self.id)
        writer.write_bool_value("isAutomated", self.is_automated)
        writer.write_bool_value("isWarmup", self.is_warmup)
        writer.write_str_value("leadId", self.lead_id)
        writer.write_str_value("leadName", self.lead_name)
        writer.write_str_value("outboundPhoneNumberId", self.outbound_phone_number_id)
        writer.write_enum_value("outboundSource", self.outbound_source)
        writer.write_str_value("providerMessageId", self.provider_message_id)
        writer.write_datetime_value("queuedAt", self.queued_at)
        writer.write_datetime_value("receivedAt", self.received_at)
        writer.write_datetime_value("scheduledFor", self.scheduled_for)
        writer.write_str_value("scheduledReason", self.scheduled_reason)
        writer.write_str_value("senderName", self.sender_name)
        writer.write_datetime_value("sendingStartedAt", self.sending_started_at)
        writer.write_datetime_value("sentAt", self.sent_at)
        writer.write_enum_value("status", self.status)
        writer.write_str_value("statusReason", self.status_reason)
        writer.write_str_value("telnyxId", self.telnyx_id)
        writer.write_str_value("tenDlcCampaignId", self.ten_dlc_campaign_id)
        writer.write_str_value("text", self.text)
        writer.write_str_value("toPhoneNumber", self.to_phone_number)
        writer.write_enum_value("trafficType", self.traffic_type)
        writer.write_datetime_value("undeliverableAt", self.undeliverable_at)
        writer.write_str_value("user", self.user)
        writer.write_str_value("userName", self.user_name)
        writer.write_additional_data_value(self.additional_data)
    

